
# Operasi Matematika & Numpy
Sebelum lanjut, harap:
1. Jika menggunakan jupyter, silahkan pilih "File" --> "Download" --> "Download .ipynb"
2. Jika menggunakan colab, silahkan pilih "File" --> "Save a copy in drive"

In [2]:
import numpy as np

### Pengenalan array

In [3]:
#1D array
a = np.array([[1, 3, 0], [2, 4, 1], [3, 6, 7]])
print('banyaknya entry = ', a.size)
print('dimensi array = ', a.ndim)
print('ukuran array = ', a.shape)

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


In [4]:
#Slicing
a[:]

array([[1, 3, 0],
       [2, 4, 1],
       [3, 6, 7]])

In [5]:
#Slicing
a[:2]

array([[1, 3, 0],
       [2, 4, 1]])

In [6]:
#Slicing
a[2]

array([3, 6, 7])

In [7]:
#Slicing
a[1:]

array([[2, 4, 1],
       [3, 6, 7]])

In [8]:
print('a[1:3] = ', a[1:3])
print('a[:3] = ', a[:3])

a[1:3] =  [[2 4 1]
 [3 6 7]]
a[:3] =  [[1 3 0]
 [2 4 1]
 [3 6 7]]


In [9]:
#2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Latihan-2 (2D array)

In [10]:
#Lengkapi kodingan berikut
print('banyaknya entry = ', a.size )
print('dimensi array = ', a.ndim )
print('ukuran array = ', a.shape )

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


In [11]:
#Slicing
print('baris ke-2 = ', A[1])
print('entry ke-2 & 3 baris ke-2 = ', A[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', A[:2, 1])

baris ke-2 =  [4 5 6]
entry ke-2 & 3 baris ke-2 =  [5 6]
entry pertama & 2 kolom ke-2 =  [2 5]


#### Latihan-3 (Slicing)

In [12]:
#Lengkapi kodingan berikut
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

baris ke-3 =  [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 =  [6 9]


output jawaban:
baris ke-3 =  [7 8 9]

entry ke-1 & 2 baris ke-3 =  [7 8]

entry ke-2 & 3 kolom ke-3 =  [6 9]

### Operasi Matematika di Numpy

In [13]:
C = A*A
print('perkalian antar entry = ')
print(C)

perkalian antar entry = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [14]:
print('perkalian matriks = ')
print(np.matmul(A,A))

perkalian matriks = 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Bisa dilihat perbedaan perkalian antar entry dan perkalian matriks biasa?

In [15]:
print('determinan matriks A = ', np.linalg.det(A))
print('determinan matriks C = ', np.linalg.det(C))

determinan matriks A =  -9.51619735392994e-16
determinan matriks C =  -216.00000000000006


In [4]:
A = np.array([[3, 1, -1], [4, 2, 7], [5, 2, 2]])
print(A)

[[ 3  1 -1]
 [ 4  2  7]
 [ 5  2  2]]


In [5]:
print('determinan matriks A = ', np.linalg.det(A))

determinan matriks A =  -1.0000000000000058


In [16]:
print('nilai dan vektor eigen matriks A = ', np.linalg.eig(A))

nilai dan vektor eigen matriks A =  (array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [17]:
print('nilai eigen matriks A = ', np.linalg.eig(A)[0])

nilai eigen matriks A =  [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]


In [18]:
print('vektor eigen matriks A = ', np.linalg.eig(A)[1])

vektor eigen matriks A =  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [19]:
e_vec = np.linalg.eig(A)[1][:, 0] #Menagambil eigen vector pertama ([-0.23197, -0.52532209, -0.8186735  ])
e_val = np.linalg.eig(A)[0][0] #Mengambil eigen value pertama (1.61168440e+01)

In [20]:
print(np.matmul(A, e_vec)) #hasil A * eigen vector

[ -3.73863537  -8.46653421 -13.19443305]


In [21]:
print(e_val*e_vec) #hasil eigen value * eigen vector (Hasilnya sama)

[ -3.73863537  -8.46653421 -13.19443305]


### Latihan-4 (Operasi matriks)

In [22]:
import numpy as np


In [23]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:
*   2*A
*   2+A
*   A+B
*   A-B
*   determinan A
*   invers dari B, simpan jadi matriks D
*   transpose D
*   nilai eigen dan vektor eigen dari A dan B







In [27]:
#Ketik Kode disini
a = 2*A
b = 2+A
c = A+B
d = A-B
det = np.linalg.det(A)
D = np.linalg.inv(B)
trans = np.transpose(D)
# egA = np.linalg.eig(A)[0]

# egB = np.linalg.eig(B)[0]

print("Hasil dari 2*A: ",a)
print("Hasil dari 2+A: ",b)
print("Hasil dari A+B: ",c)
print("Hasil dari A-B: ",d)
print("Hasil dari Determinan B: ",det)
print("Invers B : ",D)
print("Hasil dari Transpose D: ",trans)
print("Hasil dari Eigen A: ",np.linalg.eig(A)[0])
print("Hasil dari Eigen B: ",np.linalg.eig(B)[0])
print("Hasil dari Vektor A: ",np.linalg.eig(A)[1])
print("Hasil dari Vektor B: ",np.linalg.eig(B)[1])

Hasil dari 2*A:  [[ 2  4]
 [14 16]]
Hasil dari 2+A:  [[ 3  4]
 [ 9 10]]
Hasil dari A+B:  [[ 4  7]
 [ 8 14]]
Hasil dari A-B:  [[-2 -3]
 [ 6  2]]
Hasil dari Determinan B:  -6.0
Invers B :  [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]
Hasil dari Transpose D:  [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]
Hasil dari Eigen A:  [-0.62347538  9.62347538]
Hasil dari Eigen B:  [1.8074176 7.1925824]
Hasil dari Vektor A:  [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]
Hasil dari Vektor B:  [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)? 

In [25]:
#Tunjukkan bedanya di kodingan di bawah ini


output jawaban: 

perkalian entry = [[ 1.38461538, -1.92307692], [-0.07692308,  1.38461538]]

perkalian matriks = [[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]]


In [28]:
print("Perkalian entry: ",B*D)
print("Perkalian matriks: ",np.matmul(B,D))

Perkalian entry:  [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]
Perkalian matriks:  [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


In [6]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[9,7,8],[3,2,1],[6,5,4]])
z = x[:2,1:] + y[1:3,:2]
print(z)

[[ 5  5]
 [11 11]]


In [7]:
temp = [1,4,5,0,2,6,9,0,8,3,0]
x,i = 0,0
while(temp[i]!=0):
    x += temp[i]
    i += 2
print(x)

25


In [8]:
k,l,m,n,o = '7','8','3','9','6'
x = l+o
y = x+k
z = y * int(m)
print(float(z))

867867867.0


In [9]:
numbers = [-1,-2,3,4,5,-6,-7,8,9,-10,0]
score = []

for num in numbers:
    if not(num<=0) and num%2==0:
        score.append(num)
print(score)

[4, 8]


In [10]:
def hitung_nilai(absensi, tugas, ujian):
    print(absensi*0.3 + tugas*0.3 + ujian*0.4)

nilai_tambah = 10
nilai_akhir = hitung_nilai(80,80,80) + nilai_tambah

80.0


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [11]:
x = "8"
y = 2
z = x*y
print(z)

88
